- name: nework-bigip
  hosts: localhost
  connection: local
  gather_facts: no
  environment:
    F5_USER: "admin"
    F5_PASSWORD: "JSYH@founder"
    F5_VALIDATE_CERTS: "no"
 
  tasks:
  - name: Get facts from XLSX file
    xls_to_facts:
      src: ./JSBANK-BIGIP.xlsx

  - name: set mgmt IP variable
    set_fact: 
      mgmt_ip: "{{ item.mgmt }}" 
    with_items: "{{ spreadsheet_mgmt }}"

  - debug:
      msg: Server mgmt IP is {{ mgmt_ip }}

  - name: Set VLANS
    bigip_vlan:
      server: "{{ mgmt_ip }}"
      name: "{{ item.vlan_name }}"
      tag: "{{ item.vlan_id }}"
    with_items: "{{ spreadsheet_vlans}}"

  - name: Set untagged interfaces
    bigip_vlan:
      server: "{{ mgmt_ip }}"
      untagged_interface: "{{ item.untagged_interface }}"
      name: "{{ item.vlan_name }}"
    with_items: "{{ spreadsheet_vlans}}"
    when: item.untagged_interface != ''
    ignore_errors: yes

  - name: Set tagged interfaces
    bigip_vlan:
      server: "{{ mgmt_ip }}"
      tagged_interface: "{{ item.tagged_interface }}"
      name: "{{ item.vlan_name }}"
    with_nested: "{{ spreadsheet_vlans}}"
    when: item.tagged_interface != '' 
    ignore_errors: yes  

  - name: Set non-floating self IPs
    bigip_selfip:
      server: "{{ mgmt_ip}}"
      name: "{{ item.ip_address }}"
      address: "{{ item.ip_address }}"
      netmask: "{{ item.netmask }}"
      vlan: "{{ item.vlan }}"
      state: "present"
    with_items: "{{ spreadsheet_self_ips }}"
     
  - name: disable BIG-IP setup utility
    bigip_command:
      server: "{{ mgmt_ip }}"
      commands: 
        - modify /sys global-settings gui-setup disabled
        - save sys config

  - name: Add routes
    bigip_static_route:
      server: "{{ mgmt_ip }}"
      name: "{{ item.name }}"
      destination: "{{ item.destination }}"
      netmask: "{{ item.netmask }}"
      gateway_address: "{{ item.gateway_address }}"
    with_items: "{{ spreadsheet_routes }}"  